"""Bake the off-hand pistol's kick from the game's own pistol fire animations (the player, round 46: "It has no brass or
recoil"; OFFPISTOL-DESIGN 3.4, K(t)).

The gun hand's drawn gun is the game's camera-frame gun moved onto the controller (viewmodel: d = camInv x gunFrame), so
its kick is the arms' fire animation moving RightProp (the gun mesh's frame; the gun AnimSet's RootOffset stays put
through the fire) against the camera. For each pistol: K(f) = RightProp(f) x inv(RightProp(0)) in the arms' component
space -- a move in the gun mesh's own frame (pre-multiplied: RightProp(f) = K(f) x RightProp(0)) -- mirrored into the left
hand as the hold is (S K S, S = the mesh's X mirror, OFFPISTOL-DESIGN 3.2).

    python tools/pistol_kick.py <export dir> > src/mohavr/pistol_kick.inc

(<export dir>: the umodel exports reload_grips.py reads, work/research/reload.)
"""
import math
import os
import sys

import reload_grips as rg

# key, the arms' fire sequence (the one-handed pistol fires: the C96's mauser_fire, not the stocked _2 or the 712's _3)
KICKS = [
    ('Attachment_Colt45', 'colt45_fire'),
    ('Attachment_Mauser', 'mauser_fire'),
]
S = [[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]


def main(root):
    path = os.path.join(root, 'psa', 'MOHAGame', 'AnimSet', 'VM_AnimSet_NoBazooka.psa')
    arms = rg.read_psa(path)
    data = open(path, 'rb').read()
    parents = []
    for cid, dsize, dcount, p in rg._chunks(data):
        if cid.startswith('BONENAMES'):
            parents = [rg._bone(data, p + i * dsize)['parent'] for i in range(dcount)]
    names = arms['bones']

    def cs(seq, bone, f):
        i, m = names.index(bone), None
        while True:
            l = rg.key_local(arms, seq, names[i], f)
            m = l if m is None else rg.mmul(m, l)
            if i == 0 or parents[i] == i:
                return m
            i = parents[i]

    out = ['// Generated by tools/pistol_kick.py from the game\'s pistol fire animations -- do not edit. Per pistol: the',
           '// kick K(frame) in the gun mesh\'s frame, mirrored into the left hand (row-major 4x3: the X, Y, Z rows, then the',
           '// translation; engine units), at the sequence\'s rate.',
           'struct KickData {', '    const char* gun;', '    const char* seq;', '    float       rate;', '    int         frames;',
           '    float       k[32][12];', '};', 'static const KickData kKicks[] = {']
    log = []
    for key, sname in KICKS:
        s = arms['seqs'][sname]
        n = min(s['frames'], 32)
        r0 = rg.inv(cs(s, 'RightProp', 0))
        rows = []
        peak = (0.0, 0)
        for f in range(n):
            k = rg.mmul(rg.mmul(S, rg.mmul(cs(s, 'RightProp', f), r0)), S)
            ang = math.degrees(math.acos(max(-1.0, min(1.0, (k[0][0] + k[1][1] + k[2][2] - 1) / 2))))
            peak = max(peak, (ang, f))
            rows.append('{%s}' % rg.rows(k))
        out.append('    {"%s", "%s", %.3ff, %d,' % (key, sname, s['rate'], n))
        out.append('     {' + ',\n      '.join(rows) + '}},')
        log.append('%s %s: %d frames at %.1f/s, peak %.1f deg at frame %d' % (key, sname, n, s['rate'], peak[0], peak[1]))
    out.append('};')
    print('\n'.join(out))
    sys.stderr.write('\n'.join(log) + '\n')


if __name__ == '__main__':
    main(sys.argv[1])
